image: docker:stable
services:
  - docker:dind

stages:
  - Build image

docker build:
  stage: Build image
  script:
  - img build --build-arg branch=$CI_COMMIT_REF_NAME -t edcd/coriolis:$CI_COMMIT_REF_NAME .
  - echo "$REGISTRY_PASSWORD" | img login --username "$REGISTRY_USER" --password-stdin
  - img push edcd/coriolis:$CI_COMMIT_REF_NAME
