version: '2.2'

services:
  coriolis_prod:
    image: edcd/coriolis:master
    build:
      dockerfile: Dockerfile
      args:
        branch: master
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
    - web
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.basic.frontend.rule=Host:coriolis.io,coriolis.edcd.io"
    - "traefik.basic.port=80"
    - "traefik.basic.protocol=http"

  coriolis_dev:
    image: edcd/coriolis:develop
    build:
      dockerfile: Dockerfile
      args:
        branch: develop
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
    - web
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.basic.frontend.rule=Host:beta.coriolis.io,beta.coriolis.edcd.io"
    - "traefik.basic.port=80"
    - "traefik.basic.protocol=http"

  coriolis_dw2:
    image: edcd/coriolis:dw2
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
    - web
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.basic.frontend.rule=Host:dw2.coriolis.io"
    - "traefik.basic.port=80"
    - "traefik.basic.protocol=http"

networks:
  web:
    external: true
